package com.noriental.praxissvr.question.mapper;

import com.noriental.praxissvr.question.bean.EntrustUploadFile;
import com.noriental.praxissvr.question.bean.EntrustUploadFileExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface EntrustUploadFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_upload_file
     *
     * @mbggenerated
     */
    int deleteByExample(EntrustUploadFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_upload_file
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_upload_file
     *
     * @mbggenerated
     */
    int insert(EntrustUploadFile record);

    int inserts(List<EntrustUploadFile> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_upload_file
     *
     * @mbggenerated
     */
    int insertSelective(EntrustUploadFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_upload_file
     *
     * @mbggenerated
     */
    List<EntrustUploadFile> selectByExample(EntrustUploadFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_upload_file
     *
     * @mbggenerated
     */
    EntrustUploadFile selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_upload_file
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") EntrustUploadFile record, @Param("example") EntrustUploadFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_upload_file
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") EntrustUploadFile record, @Param("example") EntrustUploadFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_upload_file
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EntrustUploadFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_upload_file
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EntrustUploadFile record);
}