package com.noriental.praxissvr.question.bean;

public class EntrustUploadFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_upload_file.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_upload_file.entrust_id
     *
     * @mbggenerated
     */
    private Long entrustId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_upload_file.file_name
     *
     * @mbggenerated
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_upload_file.qiniu_url
     *
     * @mbggenerated
     */
    private String qiniuUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_upload_file.id
     *
     * @return the value of entrust_upload_file.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_upload_file.id
     *
     * @param id the value for entrust_upload_file.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_upload_file.entrust_id
     *
     * @return the value of entrust_upload_file.entrust_id
     *
     * @mbggenerated
     */
    public Long getEntrustId() {
        return entrustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_upload_file.entrust_id
     *
     * @param entrustId the value for entrust_upload_file.entrust_id
     *
     * @mbggenerated
     */
    public void setEntrustId(Long entrustId) {
        this.entrustId = entrustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_upload_file.file_name
     *
     * @return the value of entrust_upload_file.file_name
     *
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_upload_file.file_name
     *
     * @param fileName the value for entrust_upload_file.file_name
     *
     * @mbggenerated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_upload_file.qiniu_url
     *
     * @return the value of entrust_upload_file.qiniu_url
     *
     * @mbggenerated
     */
    public String getQiniuUrl() {
        return qiniuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_upload_file.qiniu_url
     *
     * @param qiniuUrl the value for entrust_upload_file.qiniu_url
     *
     * @mbggenerated
     */
    public void setQiniuUrl(String qiniuUrl) {
        this.qiniuUrl = qiniuUrl == null ? null : qiniuUrl.trim();
    }
}